# Generated by Django 2.2.2 on 2019-08-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('pic', models.ImageField(upload_to='profile_pics', verbose_name='default.jpg')),
                ('link', models.CharField(max_length=180)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Category')),
            ],
        ),
    ]
