# Generated by Django 2.2.2 on 2019-08-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20190812_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='link',
        ),
        migrations.AlterField(
            model_name='cinema',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
